language: node_js
node_js:
- "7"
- "8"
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: npm
  skip_cleanup: true
  email: tastee.is.good@gmail.com
  api_key:
    secure: c6hwJA0IT6yHuGS77WGpPKAq5fE7vjanRlUy7Cg1W8tTe8wio1081YOb3JP0EYCk/KGFQhRp2/7aqdGYIWtirXHHhjQ9LV9J+Y+YUiRMrSJ+L7kVR4UTIfP5Zq8sD5AzLseRIineP/XXZkOFVZGrRe9giRkloIWTyqIS+7IwbiBtaWIEv3TOhWTvfYav/XK1qYc+TZ1Vbc91cgO7trvYPeJHDWXx/Jr9kivb7vBpQqyPWxPK9dqh2F1Gp+k6XHcOWsrTldB1FP0fGPzfPgilp2h2Vmuki4Wd6iWTV+PkytYQEwLWbRY1/4NZbx7FP3EojupN+TG3leXsYC7zznRZAn3+RxZZNqRmDNgtCCpDcWVCBNIX8GyOwqBpZHgyHGO349B+os1lUGCpbOiahsA9J8N1rq4FYDTCPjiaYzOBU4VytQkfDgLMrIGbdRxHU3s7f1rT/G9WShH2lPkHXxhixFXKYAQcxUtP7BnjPs0xQi5bQXOJGfUFt4yzZk/wQRk9mxBx7OslBgHeS4eoHZUSTS9fYuewhG9Y2VT06cxApfJOBTIIvv3xPLo5T2kUX0vG6UBT/UZ6X63mArL/yoSyn9oGOksmx9chzOO/XJgF+JAfiQSHMc010z3kRVgNpegC4IvQXwE0t4l5j2Z02SBxy/VXWMIkbJO3aHFOBThY0Ls=
  on:
    tags: true
    repo: tastee/tastee-core
